[test_pronounce_parameters]

'-dict' = "./../Dictionaries/art_db_v3.dic"
'-phdict' = "./../Dictionaries/art_db_v3_inference.phone"
'-infolder' = "/home/dbarbera/Repositories/art_db/wav/train/art_db_compilation"
'-tests' = "./../Tests/train_inputs_v3.csv"
'-expectations' = "./../Expectations/train_expectations_v3.csv"
'-outfolder' = "./../Test_Output/output_2022-02-15T10:29:55-062_Bare_Train_set_train_expectations_v3"
'-featparams' = "./../Models/Bare/2022-02-15T10:29:55-062_Bare.ci_cont/feat.params"
'-hmm' = "./../Models/Bare/2022-02-15T10:29:55-062_Bare.ci_cont"
