[test_pronounce_parameters]

'-dict' = "./../Dictionaries/art_db_v2.dic"
'-phdict' = "./../Dictionaries/art_db_v2_inference.phone"
'-infolder' = "/home/dbarbera/Data/audio_clips"
'-tests' = "./../Tests/pronounce_input.csv"
'-expectations' = "./../Expectations/expectations_v2.csv"
'-outfolder' = "./../Test_Output/output_2022-02-07T14:11:46-092_Bare_1"
'-featparams' = "./../Models/Bare/2022-02-07T14:11:46-092_Bare.ci_cont/feat.params"
'-hmm' = "./../Models/Bare/2022-02-07T14:11:46-092_Bare.ci_cont"
