[test_pronounce_parameters]

'-dict' = "./../Dictionaries/art_db_v2.dic"
'-phdict' = "./../Dictionaries/art_db_v2_inference.phone"
'-infolder' = "/home/dbarbera/Data/audio_clips"
'-tests' = "./../Tests/pronounce_input.csv"
'-expectations' = "./../Expectations/expectations_v2.csv"
'-outfolder' = "./../Test_Output/output_Bare_loudness_tempo"
'-featparams' = "./../Models/Bare_loudness_tempo.ci_cont/feat.params"
'-hmm' = "./../Models/Bare_loudness_tempo.ci_cont"
