[test_pronounce_parameters]

'-dict' = "__DICT__"
'-phdict' = "__PHDICT__"
'-infolder' = "__AUDIOS_FOLDER__"
'-tests' = "__INPUTS__"
'-expectations' = "__EXPECTATIONS__"
'-outfolder' = "__OUTPUT_FOLDER__"
'-featparams' = "__FEAT_PARAMS__"
'-hmm' = "__HMM__"
