[Sets]
'_C_no_L_' = ["B", "D","DH","F","G","JH","K","M","N","P","R","S","SH","T","TH","V","Z","ZH","dZ","kS","tS","tR","kR","gR","pR","thR","St","kT"]
'_C_no_M_' = ["B", "D","DH","F","G","JH","K","L","N","P","R","S","SH","T","TH","V","Z","ZH","dZ","kS","tS","tR","kR","gR","pR","thR","St","kT"]
'_C_no_N_' = ["B", "D","DH","F","G","JH","K","M","L","P","R","S","SH","T","TH","V","Z","ZH","dZ","kS","tS","tR","kR","gR","pR","thR","St","kT"]

[Meta-Rules]
r1=["_C_no_L_ axL","_C_no_L_ AX L","_C_no_L_ L"]
r2=["_C_no_M_ axM","_C_no_L_ AX M","_C_no_M_ M"]
r3=["_C_no_N_ axN","_C_no_N_ AX N","_C_no_N_ N"]

[Rules]
r4=["S T S","sT S","S tS","StS"]
r5=["Y UH L","Y UW L","Yuw L","Y uwL"]
r6=["N dZ","N Z"]
r7=["iNG","IH NG"]
r8=["axN", "AX N"]
r9=["Bl","B L"]
r10=["Kl","K L"]
r11=["Kw","K W"]
r12=["Pl","P L"]
r13=["axL","AX L"]
r14=["axM","AX M"]
r15=["axN", "AX N"]
r16=["gR","G R"]
r17=["kR","K R"]
r18=["kS","K S"]
r19=["tR","T R"]
r20=["uwL","UW L"]
r21=["uwM","UW M"]
r22=["uwN","UW N"]
r23=["Yuw", "Y UW"]
r24=["sT","S T"]
r25=["dZ","D Z"]
r26=["ehL", "EH L"]
r27=["fL","F L"]
r28=["ihL","IH L"]
r29=["kT", "K T"]
r30=["thR","TH R"]